/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RandomPokemonTeamGeneratorRouteImport } from './routes/random-pokemon-team-generator'
import { Route as RandomPokemonGeneratorRouteImport } from './routes/random-pokemon-generator'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TypesIndexRouteImport } from './routes/types/index'
import { Route as PokemonIndexRouteImport } from './routes/pokemon/index'
import { Route as GenerationsIndexRouteImport } from './routes/generations/index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges/index'
import { Route as TypesTypeRouteImport } from './routes/types.$type'
import { Route as PokemonSlugRouteImport } from './routes/pokemon.$slug'
import { Route as GenerationsGenRouteImport } from './routes/generations.$gen'
import { Route as ChallengesSlugRouteImport } from './routes/challenges.$slug'

const RandomPokemonTeamGeneratorRoute =
  RandomPokemonTeamGeneratorRouteImport.update({
    id: '/random-pokemon-team-generator',
    path: '/random-pokemon-team-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const RandomPokemonGeneratorRoute = RandomPokemonGeneratorRouteImport.update({
  id: '/random-pokemon-generator',
  path: '/random-pokemon-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TypesIndexRoute = TypesIndexRouteImport.update({
  id: '/types/',
  path: '/types/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonIndexRoute = PokemonIndexRouteImport.update({
  id: '/pokemon/',
  path: '/pokemon/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationsIndexRoute = GenerationsIndexRouteImport.update({
  id: '/generations/',
  path: '/generations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const TypesTypeRoute = TypesTypeRouteImport.update({
  id: '/types/$type',
  path: '/types/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonSlugRoute = PokemonSlugRouteImport.update({
  id: '/pokemon/$slug',
  path: '/pokemon/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationsGenRoute = GenerationsGenRouteImport.update({
  id: '/generations/$gen',
  path: '/generations/$gen',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesSlugRoute = ChallengesSlugRouteImport.update({
  id: '/challenges/$slug',
  path: '/challenges/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/daily': typeof DailyRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/random-pokemon-generator': typeof RandomPokemonGeneratorRoute
  '/random-pokemon-team-generator': typeof RandomPokemonTeamGeneratorRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/generations/$gen': typeof GenerationsGenRoute
  '/pokemon/$slug': typeof PokemonSlugRoute
  '/types/$type': typeof TypesTypeRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/generations/': typeof GenerationsIndexRoute
  '/pokemon/': typeof PokemonIndexRoute
  '/types/': typeof TypesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/daily': typeof DailyRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/random-pokemon-generator': typeof RandomPokemonGeneratorRoute
  '/random-pokemon-team-generator': typeof RandomPokemonTeamGeneratorRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/generations/$gen': typeof GenerationsGenRoute
  '/pokemon/$slug': typeof PokemonSlugRoute
  '/types/$type': typeof TypesTypeRoute
  '/challenges': typeof ChallengesIndexRoute
  '/generations': typeof GenerationsIndexRoute
  '/pokemon': typeof PokemonIndexRoute
  '/types': typeof TypesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/daily': typeof DailyRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/random-pokemon-generator': typeof RandomPokemonGeneratorRoute
  '/random-pokemon-team-generator': typeof RandomPokemonTeamGeneratorRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/generations/$gen': typeof GenerationsGenRoute
  '/pokemon/$slug': typeof PokemonSlugRoute
  '/types/$type': typeof TypesTypeRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/generations/': typeof GenerationsIndexRoute
  '/pokemon/': typeof PokemonIndexRoute
  '/types/': typeof TypesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact-us'
    | '/daily'
    | '/favorites'
    | '/history'
    | '/random-pokemon-generator'
    | '/random-pokemon-team-generator'
    | '/challenges/$slug'
    | '/generations/$gen'
    | '/pokemon/$slug'
    | '/types/$type'
    | '/challenges/'
    | '/generations/'
    | '/pokemon/'
    | '/types/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact-us'
    | '/daily'
    | '/favorites'
    | '/history'
    | '/random-pokemon-generator'
    | '/random-pokemon-team-generator'
    | '/challenges/$slug'
    | '/generations/$gen'
    | '/pokemon/$slug'
    | '/types/$type'
    | '/challenges'
    | '/generations'
    | '/pokemon'
    | '/types'
  id:
    | '__root__'
    | '/'
    | '/contact-us'
    | '/daily'
    | '/favorites'
    | '/history'
    | '/random-pokemon-generator'
    | '/random-pokemon-team-generator'
    | '/challenges/$slug'
    | '/generations/$gen'
    | '/pokemon/$slug'
    | '/types/$type'
    | '/challenges/'
    | '/generations/'
    | '/pokemon/'
    | '/types/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactUsRoute: typeof ContactUsRoute
  DailyRoute: typeof DailyRoute
  FavoritesRoute: typeof FavoritesRoute
  HistoryRoute: typeof HistoryRoute
  RandomPokemonGeneratorRoute: typeof RandomPokemonGeneratorRoute
  RandomPokemonTeamGeneratorRoute: typeof RandomPokemonTeamGeneratorRoute
  ChallengesSlugRoute: typeof ChallengesSlugRoute
  GenerationsGenRoute: typeof GenerationsGenRoute
  PokemonSlugRoute: typeof PokemonSlugRoute
  TypesTypeRoute: typeof TypesTypeRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
  GenerationsIndexRoute: typeof GenerationsIndexRoute
  PokemonIndexRoute: typeof PokemonIndexRoute
  TypesIndexRoute: typeof TypesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/random-pokemon-team-generator': {
      id: '/random-pokemon-team-generator'
      path: '/random-pokemon-team-generator'
      fullPath: '/random-pokemon-team-generator'
      preLoaderRoute: typeof RandomPokemonTeamGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random-pokemon-generator': {
      id: '/random-pokemon-generator'
      path: '/random-pokemon-generator'
      fullPath: '/random-pokemon-generator'
      preLoaderRoute: typeof RandomPokemonGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/types/': {
      id: '/types/'
      path: '/types'
      fullPath: '/types/'
      preLoaderRoute: typeof TypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/': {
      id: '/pokemon/'
      path: '/pokemon'
      fullPath: '/pokemon/'
      preLoaderRoute: typeof PokemonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations/': {
      id: '/generations/'
      path: '/generations'
      fullPath: '/generations/'
      preLoaderRoute: typeof GenerationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/types/$type': {
      id: '/types/$type'
      path: '/types/$type'
      fullPath: '/types/$type'
      preLoaderRoute: typeof TypesTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/$slug': {
      id: '/pokemon/$slug'
      path: '/pokemon/$slug'
      fullPath: '/pokemon/$slug'
      preLoaderRoute: typeof PokemonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations/$gen': {
      id: '/generations/$gen'
      path: '/generations/$gen'
      fullPath: '/generations/$gen'
      preLoaderRoute: typeof GenerationsGenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$slug': {
      id: '/challenges/$slug'
      path: '/challenges/$slug'
      fullPath: '/challenges/$slug'
      preLoaderRoute: typeof ChallengesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactUsRoute: ContactUsRoute,
  DailyRoute: DailyRoute,
  FavoritesRoute: FavoritesRoute,
  HistoryRoute: HistoryRoute,
  RandomPokemonGeneratorRoute: RandomPokemonGeneratorRoute,
  RandomPokemonTeamGeneratorRoute: RandomPokemonTeamGeneratorRoute,
  ChallengesSlugRoute: ChallengesSlugRoute,
  GenerationsGenRoute: GenerationsGenRoute,
  PokemonSlugRoute: PokemonSlugRoute,
  TypesTypeRoute: TypesTypeRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
  GenerationsIndexRoute: GenerationsIndexRoute,
  PokemonIndexRoute: PokemonIndexRoute,
  TypesIndexRoute: TypesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
