/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RandomPokemonTeamGeneratorRouteImport } from './routes/random-pokemon-team-generator'
import { Route as RandomPokemonGeneratorRouteImport } from './routes/random-pokemon-generator'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TypesTypeRouteImport } from './routes/types.$type'
import { Route as PokemonSlugRouteImport } from './routes/pokemon.$slug'
import { Route as GenerationsGenRouteImport } from './routes/generations.$gen'
import { Route as ChallengesSlugRouteImport } from './routes/challenges.$slug'

const RandomPokemonTeamGeneratorRoute =
  RandomPokemonTeamGeneratorRouteImport.update({
    id: '/random-pokemon-team-generator',
    path: '/random-pokemon-team-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const RandomPokemonGeneratorRoute = RandomPokemonGeneratorRouteImport.update({
  id: '/random-pokemon-generator',
  path: '/random-pokemon-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TypesTypeRoute = TypesTypeRouteImport.update({
  id: '/types/$type',
  path: '/types/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonSlugRoute = PokemonSlugRouteImport.update({
  id: '/pokemon/$slug',
  path: '/pokemon/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationsGenRoute = GenerationsGenRouteImport.update({
  id: '/generations/$gen',
  path: '/generations/$gen',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesSlugRoute = ChallengesSlugRouteImport.update({
  id: '/challenges/$slug',
  path: '/challenges/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/random-pokemon-generator': typeof RandomPokemonGeneratorRoute
  '/random-pokemon-team-generator': typeof RandomPokemonTeamGeneratorRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/generations/$gen': typeof GenerationsGenRoute
  '/pokemon/$slug': typeof PokemonSlugRoute
  '/types/$type': typeof TypesTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/random-pokemon-generator': typeof RandomPokemonGeneratorRoute
  '/random-pokemon-team-generator': typeof RandomPokemonTeamGeneratorRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/generations/$gen': typeof GenerationsGenRoute
  '/pokemon/$slug': typeof PokemonSlugRoute
  '/types/$type': typeof TypesTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/random-pokemon-generator': typeof RandomPokemonGeneratorRoute
  '/random-pokemon-team-generator': typeof RandomPokemonTeamGeneratorRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/generations/$gen': typeof GenerationsGenRoute
  '/pokemon/$slug': typeof PokemonSlugRoute
  '/types/$type': typeof TypesTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daily'
    | '/favorites'
    | '/history'
    | '/random-pokemon-generator'
    | '/random-pokemon-team-generator'
    | '/challenges/$slug'
    | '/generations/$gen'
    | '/pokemon/$slug'
    | '/types/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daily'
    | '/favorites'
    | '/history'
    | '/random-pokemon-generator'
    | '/random-pokemon-team-generator'
    | '/challenges/$slug'
    | '/generations/$gen'
    | '/pokemon/$slug'
    | '/types/$type'
  id:
    | '__root__'
    | '/'
    | '/daily'
    | '/favorites'
    | '/history'
    | '/random-pokemon-generator'
    | '/random-pokemon-team-generator'
    | '/challenges/$slug'
    | '/generations/$gen'
    | '/pokemon/$slug'
    | '/types/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailyRoute: typeof DailyRoute
  FavoritesRoute: typeof FavoritesRoute
  HistoryRoute: typeof HistoryRoute
  RandomPokemonGeneratorRoute: typeof RandomPokemonGeneratorRoute
  RandomPokemonTeamGeneratorRoute: typeof RandomPokemonTeamGeneratorRoute
  ChallengesSlugRoute: typeof ChallengesSlugRoute
  GenerationsGenRoute: typeof GenerationsGenRoute
  PokemonSlugRoute: typeof PokemonSlugRoute
  TypesTypeRoute: typeof TypesTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/random-pokemon-team-generator': {
      id: '/random-pokemon-team-generator'
      path: '/random-pokemon-team-generator'
      fullPath: '/random-pokemon-team-generator'
      preLoaderRoute: typeof RandomPokemonTeamGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random-pokemon-generator': {
      id: '/random-pokemon-generator'
      path: '/random-pokemon-generator'
      fullPath: '/random-pokemon-generator'
      preLoaderRoute: typeof RandomPokemonGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/types/$type': {
      id: '/types/$type'
      path: '/types/$type'
      fullPath: '/types/$type'
      preLoaderRoute: typeof TypesTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/$slug': {
      id: '/pokemon/$slug'
      path: '/pokemon/$slug'
      fullPath: '/pokemon/$slug'
      preLoaderRoute: typeof PokemonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations/$gen': {
      id: '/generations/$gen'
      path: '/generations/$gen'
      fullPath: '/generations/$gen'
      preLoaderRoute: typeof GenerationsGenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$slug': {
      id: '/challenges/$slug'
      path: '/challenges/$slug'
      fullPath: '/challenges/$slug'
      preLoaderRoute: typeof ChallengesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailyRoute: DailyRoute,
  FavoritesRoute: FavoritesRoute,
  HistoryRoute: HistoryRoute,
  RandomPokemonGeneratorRoute: RandomPokemonGeneratorRoute,
  RandomPokemonTeamGeneratorRoute: RandomPokemonTeamGeneratorRoute,
  ChallengesSlugRoute: ChallengesSlugRoute,
  GenerationsGenRoute: GenerationsGenRoute,
  PokemonSlugRoute: PokemonSlugRoute,
  TypesTypeRoute: TypesTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
